### ISSUE TITLE
Too high of memory usage in 6 to 8 depot assignment cases

### ISSUE THREAD

**Issue by shuyao-guo** [mpm-tu-berlin/eflips-opt#4]
We must find a way to reduce the memory consumption by:

- re-build constraints
- immigrate to gamspy (assuming it has better memory management)

Updates: temporarily a better construction of constraint "depot-capacity-constraint" is built by @ludgerheide  and the performance is approx. 10 times increased. See if there are potential options

**Comment by ludgerheide** [comment]
Finished. Removed lots of zeros
